### ISSUE TITLE
Enlever le jar SDKClient lors de l'upload

### ISSUE THREAD

**Issue by wtoscer** [vdoc-community/vdoc-maven-plugin#13]
Ce jar est un peu inutile, il est même contreproductif

**Comment by famaridon** [comment]
il faut ajouter un FileFilter qui prend une liste de fichier a exclure

**Comment by famaridon** [comment]
Mojo is deleted we use maven deploy

**Comment by famaridon** [comment]
Mojo is deleted we use maven deploy
