### ISSUE TITLE
Ne pas prendre en compte les putains de fichiers temporaires office lors de la création du setup

### ISSUE THREAD

**Issue by wtoscer** [vdoc-community/vdoc-maven-plugin#15]
Sinon, ça plante en fait, connerie de word et d'excel...
Voir si on peut ne pas prendre les fichiers qui commencent par un "~"

**Comment by wtoscer** [comment]
C'est surtout excel en fait, word n'a pas l'air de bloquer...

**Comment by famaridon** [comment]
J'ai ajouter une exclusion sur tous les fichier qui commence par ~ comme cela il est possible d'ignorer les fichier que l'on veux
