### ISSUE TITLE
Ajouter des apps dans le setup

### ISSUE THREAD

**Issue by IssaNissa** [vdoc-community/vdoc-maven-plugin#16]
Aujourd'hui, pour intégrer des apps autres dans les setups (add-ons, ...), on est obligé de le faire à la main, donc risque d'erreurs...
On avait essayé rapidement de modifier le traitement, mais il y avait une erreur lors du traitement du zip (il me semple...).

**Comment by famaridon** [comment]
Hello,

actualy each provided dependency with "setup" classifier on maven repo is merge into the current setup
